modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="MIT for code, assets are CC BY-NC-SA"
issueTrackerURL="https://github.com/seymourimadeit/Piglin-Proliferation" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="piglinproliferation" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
# see the associated build.gradle script for how to populate this completely automatically during a build
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="Piglin Proliferation" #mandatory
updateJSONURL="https://raw.githubusercontent.com/seymourimadeit/Piglin-Proliferation/main/update.json" #optional
# logoFile="piglinproliferation.png" #optional
credits="TallestEgg, Edmord for the non-buckler art, Vivi for buckler art" #optional
description='''
Piglins expanded in new ways!
'''
[[dependencies.piglinproliferation]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43.1.42,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.piglinproliferation]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"
